<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class AsinImages extends Dto
{
    /**
     * @param  AsinImage  $asinImage  A single ASIN product with its associated image.
     */
    public function __construct(
        public AsinImage $asinImage,
    ) {}
}
