<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class BrandStoryMediaAssetModule extends Dto
{
    /**
     * @param  ImageComponent  $image  A reference to an image, hosted in the A+ Content media library.
     * @param  ?TextComponent  $title  Rich text content.
     * @param  ?ParagraphComponent  $description  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public ImageComponent $image,
        public ?TextComponent $title = null,
        public ?ParagraphComponent $description = null,
    ) {}
}
