<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class BrandStoryFourAsinModule extends Dto
{
    protected static array $complexArrayTypes = ['asinImages' => AsinImages::class];

    /**
     * @param  TextComponent  $title  Rich text content.
     * @param  AsinImages[]  $asinImages  Exactly 4 ASIN image entries.
     * @param  ?TextComponent  $brandStoreId  Rich text content.
     */
    public function __construct(
        public TextComponent $title,
        public array $asinImages,
        public ?TextComponent $brandStoreId = null,
    ) {}
}
