<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class BrandStoryQuestionsModule extends Dto
{
    protected static array $complexArrayTypes = ['questionAnswerPairs' => QuestionAnswerPairs::class];

    /**
     * @param  QuestionAnswerPairs[]  $questionAnswerPairs  Exactly 3 question-answer pairs.
     */
    public function __construct(
        public array $questionAnswerPairs,
    ) {}
}
