<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ComparisonProducts extends Dto
{
    /**
     * @param  ComparisonProduct  $comparisonProduct  A product in the comparison table carousel modules.
     */
    public function __construct(
        public ComparisonProduct $comparisonProduct,
    ) {}
}
