<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ComparisonRow extends Dto
{
    protected static array $complexArrayTypes = ['comparisonFields' => ComparisonFields::class];

    /**
     * @param  ?int  $position  The position of the comparison row.
     * @param  ?TextComponent  $metricName  Rich text content.
     * @param  ?TextComponent  $comparisonType  Rich text content.
     * @param  ?TextComponent  $additionalInfo  Rich text content.
     * @param  ComparisonFields[]|null  $comparisonFields  Collection of comparison field values, one set per product.
     */
    public function __construct(
        public ?int $position = null,
        public ?TextComponent $metricName = null,
        public ?TextComponent $comparisonType = null,
        public ?TextComponent $additionalInfo = null,
        public ?array $comparisonFields = null,
    ) {}
}
