<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ComparisonMetrics extends Dto
{
    /**
     * @param  ComparisonRow  $comparisonRow  Comparison row for table-based comparison modules.
     */
    public function __construct(
        public ComparisonRow $comparisonRow,
    ) {}
}
