<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ComparisonProduct extends Dto
{
    /**
     * @param  ?int  $position  The position of the product in comparison display.
     * @param  ?TextComponent  $productTitle  Rich text content.
     * @param  ?TextComponent  $productAsin  Rich text content.
     * @param  ?ImageComponent  $desktopImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ?ImageComponent  $mobileImage  A reference to an image, hosted in the A+ Content media library.
     */
    public function __construct(
        public ?int $position = null,
        public ?TextComponent $productTitle = null,
        public ?TextComponent $productAsin = null,
        public ?ImageComponent $desktopImage = null,
        public ?ImageComponent $mobileImage = null,
    ) {}
}
