<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class CreateMediaRequest extends Dto
{
    protected static array $complexArrayTypes = [
        'descriptions' => Description::class,
        'relatedMedia' => RelatedMediaInput::class,
    ];

    /**
     * @param  string  $mediaType  The type of media asset.
     * @param  ?string  $uploadDestinationId  The S3 upload destination identifier from the `createUploadDestination` operation. Mutually exclusive with `mediaId`.
     * @param  ?string  $mediaId  An existing media asset identifier for reuse. Mutually exclusive with `uploadDestinationId`.
     * @param  ?string  $title  An optional title for the media asset. For standalone images, defaults to filename if not provided. Not applicable for videos (video title is derived from the filename).
     * @param  Description[]|null  $descriptions  A list of locale-keyed accessibility descriptions. At least one entry is required for video assets.
     * @param  RelatedMediaInput[]|null  $relatedMedia  A list of related media inputs for creation.
     */
    public function __construct(
        public string $mediaType,
        public ?string $uploadDestinationId = null,
        public ?string $mediaId = null,
        public ?string $title = null,
        public ?array $descriptions = null,
        public ?array $relatedMedia = null,
    ) {}
}
