<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class Description extends Dto
{
    /**
     * @param  string  $locale  A locale identifier (for example, `en-US`, `de-DE`).
     * @param  string  $value  The accessibility description text for the locale.
     */
    public function __construct(
        public string $locale,
        public string $value,
    ) {}
}
