<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class Faqs extends Dto
{
    /**
     * @param  Faq  $faq  A single frequently asked question with its corresponding answer.
     */
    public function __construct(
        public Faq $faq,
    ) {}
}
