<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ImageColumns extends Dto
{
    /**
     * @param  ImageColumn  $imageColumn  A single column within a multi-column premium image module, containing an image, an optional headline, and an optional description.
     */
    public function __construct(
        public ImageColumn $imageColumn,
    ) {}
}
