<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ImageTextHotSpot extends Dto
{
    /**
     * @param  ImageComponent  $mobileImage  A reference to an image, hosted in the A+ Content media library.
     * @param  TextComponent  $title  Rich text content.
     * @param  TextComponent  $xCoordinate  Rich text content.
     * @param  TextComponent  $yCoordinate  Rich text content.
     */
    public function __construct(
        public ImageComponent $mobileImage,
        public TextComponent $title,
        public TextComponent $xCoordinate,
        public TextComponent $yCoordinate,
    ) {}
}
