<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ImageCarouselPanels extends Dto
{
    /**
     * @param  ImageCarouselPanel  $imagePanel  A single panel within the image carousel that features rich text elements, a direct link to a product ASIN, and an image.
     */
    public function __construct(
        public ImageCarouselPanel $imagePanel,
    ) {}
}
