<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ImageCarouselPanel extends Dto
{
    /**
     * @param  int  $position  The position of the panel within the carousel. Must be a value between 1 and 6.
     * @param  ImageComponent  $desktopImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ImageComponent  $mobileImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ?TextComponent  $title  Rich text content.
     * @param  ?TextComponent  $buttonText  Rich text content.
     * @param  ?TextComponent  $asin  Rich text content.
     * @param  ?ParagraphComponent  $description  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public int $position,
        public ImageComponent $desktopImage,
        public ImageComponent $mobileImage,
        public ?TextComponent $title = null,
        public ?TextComponent $buttonText = null,
        public ?TextComponent $asin = null,
        public ?ParagraphComponent $description = null,
    ) {}
}
