<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ImageHotSpots extends Dto
{
    /**
     * @param  ImageHotSpot  $imageHotSpot  A hotspot with mobile image, title, description, and coordinates.
     */
    public function __construct(
        public ImageHotSpot $imageHotSpot,
    ) {}
}
