<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class Issue extends Dto
{
    /**
     * @param  string  $code  An issue code that identifies the type of issue.
     * @param  string  $message  A message that describes the issue.
     * @param  string  $severity  The severity of the issue.
     * @param  string[]  $categories  List of issue categories.
     *
     * **Possible values:**
     *
     * * `PROCESSING_ISSUE` - Media file could not be processed (codec, duration, corrupt file).
     *
     * * `CONTENT_POLICY` - Media asset is subject to content policy restrictions.
     *
     * * `METADATA_VALIDATION` - Media metadata does not meet requirements (title, descriptions).
     * @param  ?string[]  $propertyNames  Names of the properties associated with the issue, if applicable.
     */
    public function __construct(
        public string $code,
        public string $message,
        public string $severity,
        public array $categories,
        public ?array $propertyNames = null,
    ) {}
}
