<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class MediaInput extends Dto
{
    /**
     * @param  string  $mediaType  The type of media asset.
     * @param  ?string  $uploadDestinationId  The S3 upload destination identifier from the `createUploadDestination` operation, for a newly uploaded asset. Mutually exclusive with `mediaId`.
     * @param  ?string  $mediaId  An existing media asset identifier for reuse in a new association. Mutually exclusive with `uploadDestinationId`.
     * @param  ?string  $title  An optional title for the media asset. Defaults to the filename if not provided.
     */
    public function __construct(
        public string $mediaType,
        public ?string $uploadDestinationId = null,
        public ?string $mediaId = null,
        public ?string $title = null,
    ) {}
}
