<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class Media extends Dto
{
    protected static array $complexArrayTypes = [
        'descriptions' => Description::class,
        'issues' => Issue::class,
        'relatedMedia' => RelatedMedia::class,
    ];

    /**
     * @param  string  $mediaId  The unique identifier for the media asset.
     * @param  string  $mediaType  The type of media asset.
     * @param  string  $title  The title for the media asset. For videos, this is the original filename. For images, this is the user-provided title or filename.
     * @param  string[]  $status  The composite status of the media asset. Multiple statuses can apply simultaneously to represent both the workflow stage and the responsible actor.
     * @param  Description[]|null  $descriptions  A list of locale-keyed accessibility descriptions. At least one entry is required for video assets.
     * @param  ?string  $mediaUrl  The CDN URL for downloading or viewing the media asset. The URL is provisioned at upload time and available in all statuses. The media is non-permanent; you should re-retrieve using `getMedia` rather than caching indefinitely.
     * @param  Issue[]|null  $issues  A list of issues associated with a media asset or pairing.
     * @param  RelatedMedia[]|null  $relatedMedia  A list of related media associations.
     */
    public function __construct(
        public string $mediaId,
        public string $mediaType,
        public string $title,
        public array $status,
        public ?array $descriptions = null,
        public ?string $mediaUrl = null,
        public ?array $issues = null,
        public ?array $relatedMedia = null,
    ) {}
}
