<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class MetricValueItem extends Dto
{
    /**
     * @param  ?TextComponent  $metricName  Rich text content.
     * @param  ?ParagraphComponent  $metricValue  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public ?TextComponent $metricName = null,
        public ?ParagraphComponent $metricValue = null,
    ) {}
}
