<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class NavigationCarouselPanels extends Dto
{
    /**
     * @param  NavigationCarouselPanel  $navigationPanel  A single panel within the navigation carousel that features rich text elements and an image.
     */
    public function __construct(
        public NavigationCarouselPanel $navigationPanel,
    ) {}
}
