<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumTechSpecsModule extends Dto
{
    protected static array $complexArrayTypes = ['techSpecs' => TechSpecs::class];

    /**
     * @param  TextComponent  $headline  Rich text content.
     * @param  TechSpecs[]  $techSpecs  The collection of technical specifications, which must contain between 4 and 16 technical specifications.
     * @param  ?int  $columnCount  The number of columns to display in the technical specifications table, with options between 1 and 2 columns.
     */
    public function __construct(
        public TextComponent $headline,
        public array $techSpecs,
        public ?int $columnCount = null,
    ) {}
}
