<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumImageCarouselModule extends Dto
{
    protected static array $complexArrayTypes = ['carouselCards' => ImageCarouselPanels::class];

    /**
     * @param  ImageCarouselPanels[]  $carouselCards  The collection of image panels, which must contain between 2 and 6 panels.
     * @param  ?TextComponent  $headline  Rich text content.
     * @param  ?ParagraphComponent  $footer  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public array $carouselCards,
        public ?TextComponent $headline = null,
        public ?ParagraphComponent $footer = null,
    ) {}
}
