<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumFullBackgroundImageModule extends Dto
{
    /**
     * @param  ImageComponent  $desktopImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ImageComponent  $mobileImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ?TextComponent  $headline  Rich text content.
     * @param  ?ParagraphComponent  $footer  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public ImageComponent $desktopImage,
        public ImageComponent $mobileImage,
        public ?TextComponent $headline = null,
        public ?ParagraphComponent $footer = null,
    ) {}
}
