<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumNavigationCarouselModule extends Dto
{
    protected static array $complexArrayTypes = ['carouselCards' => NavigationCarouselPanels::class];

    /**
     * @param  NavigationCarouselPanels[]  $carouselCards  The collection of navigation panels, which must contain between 2 and 5 panels.
     */
    public function __construct(
        public array $carouselCards,
    ) {}
}
