<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumHotspotImageModule extends Dto
{
    protected static array $complexArrayTypes = ['hotSpots' => ImageHotSpots::class];

    /**
     * @param  ImageComponent  $desktopImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ImageHotSpots[]  $hotSpots  The collection of hotspots, which must contain between 2 and 6 hotspots.
     */
    public function __construct(
        public ImageComponent $desktopImage,
        public array $hotSpots,
    ) {}
}
