<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumFaqModule extends Dto
{
    protected static array $complexArrayTypes = ['faqs' => Faqs::class];

    /**
     * @param  Faqs[]  $faqs  The collection of FAQ entries, which must contain between 2 and 5 FAQs.
     * @param  ?string  $colorType  The relative color scheme of content.
     */
    public function __construct(
        public array $faqs,
        public ?string $colorType = null,
    ) {}
}
