<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumComparisonScrollerModule extends Dto
{
    protected static array $attributeMap = ['showAtc' => 'showATC'];

    protected static array $complexArrayTypes = [
        'comparisonProducts' => ComparisonProducts::class,
        'comparisonRows' => ComparisonMetrics::class,
    ];

    /**
     * @param  TextComponent  $headline  Rich text content.
     * @param  ComparisonProducts[]  $comparisonProducts  The collection of comparison products, which must contain between 3 and 7 products.
     * @param  ComparisonMetrics[]  $comparisonRows  The collection of comparison rows, which must contain between 5 and 12 rows.
     * @param  ?bool  $showAtc  Whether to show Add to Cart buttons.
     * @param  ?bool  $showPrices  Whether to show product prices.
     * @param  ?bool  $showReviews  Whether to show product reviews.
     */
    public function __construct(
        public TextComponent $headline,
        public array $comparisonProducts,
        public array $comparisonRows,
        public ?bool $showAtc = null,
        public ?bool $showPrices = null,
        public ?bool $showReviews = null,
    ) {}
}
