<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumVideoTextModule extends Dto
{
    /**
     * @param  string  $positionType  The relative positioning of content.
     * @param  TextComponent  $headline  Rich text content.
     * @param  VideoComponent  $video  A reference to a video asset hosted within A+, including metadata and a preview thumbnail image.
     * @param  ?TextComponent  $title  Rich text content.
     * @param  ?ParagraphComponent  $description  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public string $positionType,
        public TextComponent $headline,
        public VideoComponent $video,
        public ?TextComponent $title = null,
        public ?ParagraphComponent $description = null,
    ) {}
}
