<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumDualImageTextModule extends Dto
{
    protected static array $complexArrayTypes = ['columns' => ImageColumns::class];

    /**
     * @param  ImageColumns[]  $columns  The collection of image columns, which must contain exactly 2 columns.
     * @param  ?TextComponent  $headline  Rich text content.
     */
    public function __construct(
        public array $columns,
        public ?TextComponent $headline = null,
    ) {}
}
