<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumThreeColumnComparisonModule extends Dto
{
    protected static array $complexArrayTypes = [
        'comparisonProducts' => ThreeColumnComparisonProduct::class,
        'comparisonRows' => ThreeColumnComparisonRow::class,
    ];

    /**
     * @param  TextComponent  $headline  Rich text content.
     * @param  ThreeColumnComparisonProduct[]  $comparisonProducts  The three products being compared. Exactly three products are required.
     * @param  ThreeColumnComparisonRow[]  $comparisonRows  The rows of the comparison table. Each row represents a metric compared across all three products.
     */
    public function __construct(
        public TextComponent $headline,
        public array $comparisonProducts,
        public array $comparisonRows,
    ) {}
}
