<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumVideoImageCarouselModule extends Dto
{
    protected static array $complexArrayTypes = ['carouselCards' => VideoImageCarouselPanels::class];

    /**
     * @param  VideoImageCarouselPanels[]  $carouselCards  The list of carousel panels, between 2 and 6 items.
     * @param  ?TextComponent  $headline  Rich text content.
     */
    public function __construct(
        public array $carouselCards,
        public ?TextComponent $headline = null,
    ) {}
}
