<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumHotspotImageTextModule extends Dto
{
    protected static array $complexArrayTypes = ['hotSpots' => ImageTextHotSpots::class];

    /**
     * @param  TextComponent  $headline  Rich text content.
     * @param  ImageComponent  $desktopImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ImageTextHotSpots[]  $hotSpots  The collection of hotspots, which must contain between 2 and 6 hotspots.
     * @param  ?ParagraphComponent  $mainDescription  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public TextComponent $headline,
        public ImageComponent $desktopImage,
        public array $hotSpots,
        public ?ParagraphComponent $mainDescription = null,
    ) {}
}
