<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumComparisonCarouselModule extends Dto
{
    protected static array $complexArrayTypes = [
        'comparisonProducts' => ComparisonProducts::class,
        'comparisonMetrics' => ComparisonMetrics::class,
    ];

    /**
     * @param  TextComponent  $headline  Rich text content.
     * @param  ComparisonProducts[]  $comparisonProducts  The collection of comparison products, which must contain between 3 and 5 products.
     * @param  ComparisonMetrics[]  $comparisonMetrics  The collection of comparison metrics, which must contain between 3 and 7 metrics.
     */
    public function __construct(
        public TextComponent $headline,
        public array $comparisonProducts,
        public array $comparisonMetrics,
    ) {}
}
