<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumTextModule extends Dto
{
    /**
     * @param  ParagraphComponent  $description  A list of rich text content, usually presented in a text box.
     * @param  ?TextComponent  $headline  Rich text content.
     */
    public function __construct(
        public ParagraphComponent $description,
        public ?TextComponent $headline = null,
    ) {}
}
