<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumRegimenCarouselModule extends Dto
{
    protected static array $complexArrayTypes = ['carouselCards' => RegimenCarouselPanels::class];

    /**
     * @param  RegimenCarouselPanels[]  $carouselCards  The collection of regimen panels, which must contain between 2 and 5 panels.
     * @param  ?TextComponent  $headline  Rich text content.
     */
    public function __construct(
        public array $carouselCards,
        public ?TextComponent $headline = null,
    ) {}
}
