<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumFullBackgroundTextModule extends Dto
{
    /**
     * @param  string  $positionType  The relative positioning of content.
     * @param  string  $colorType  The relative color scheme of content.
     * @param  ImageComponent  $desktopImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ImageComponent  $mobileImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ?TextComponent  $subheadline  Rich text content.
     * @param  ?TextComponent  $headline  Rich text content.
     * @param  ?ParagraphComponent  $description  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public string $positionType,
        public string $colorType,
        public ImageComponent $desktopImage,
        public ImageComponent $mobileImage,
        public ?TextComponent $subheadline = null,
        public ?TextComponent $headline = null,
        public ?ParagraphComponent $description = null,
    ) {}
}
