<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumImageTextModule extends Dto
{
    /**
     * @param  string  $positionType  The relative positioning of content.
     * @param  TextComponent  $headline  Rich text content.
     * @param  ImageComponent  $image  A reference to an image, hosted in the A+ Content media library.
     * @param  ?TextComponent  $subheadline  Rich text content.
     * @param  ?ParagraphComponent  $bodyText  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public string $positionType,
        public TextComponent $headline,
        public ImageComponent $image,
        public ?TextComponent $subheadline = null,
        public ?ParagraphComponent $bodyText = null,
    ) {}
}
