<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class PremiumHeroVideoModule extends Dto
{
    /**
     * @param  VideoComponent  $heroVideo  A reference to a video asset hosted within A+, including metadata and a preview thumbnail image.
     * @param  ?TextComponent  $headline  Rich text content.
     * @param  ?ParagraphComponent  $footer  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public VideoComponent $heroVideo,
        public ?TextComponent $headline = null,
        public ?ParagraphComponent $footer = null,
    ) {}
}
