<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class QuestionAnswerPair extends Dto
{
    /**
     * @param  TextComponent  $question  Rich text content.
     * @param  ParagraphComponent  $answer  A list of rich text content, usually presented in a text box.
     */
    public function __construct(
        public TextComponent $question,
        public ParagraphComponent $answer,
    ) {}
}
