<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class RegimenCarouselPanels extends Dto
{
    /**
     * @param  RegimenCarouselPanel  $regimenPanel  A single panel within the regimen carousel that features rich text elements and an image.
     */
    public function __construct(
        public RegimenCarouselPanel $regimenPanel,
    ) {}
}
