<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class RelatedMediaInput extends Dto
{
    /**
     * @param  string  $associationType  The type of relationship between media assets.
     * @param  string  $title  The title for this pairing. Minimum three words for `VIDEO_PAIRING`; must not be all capital letters.
     * @param  MediaInput  $media  Input for referencing a media asset during creation. Exactly one of `uploadDestinationId` or `mediaId` must be provided.
     */
    public function __construct(
        public string $associationType,
        public string $title,
        public MediaInput $media,
    ) {}
}
