<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class RelatedMedia extends Dto
{
    protected static array $complexArrayTypes = ['issues' => Issue::class];

    /**
     * @param  string  $associationType  The type of relationship between media assets.
     * @param  string  $title  The title for this pairing. For `VIDEO_PAIRING`, this is the user-provided pairing title. Minimum three words; must not be all capital letters.
     * @param  string[]  $status  The composite status of this pairing. Multiple statuses can apply simultaneously to represent both the workflow stage and the responsible actor.
     * @param  MediaInfo  $media  The core media entity attributes without associations.
     * @param  Issue[]|null  $issues  A list of issues associated with a media asset or pairing.
     */
    public function __construct(
        public string $associationType,
        public string $title,
        public array $status,
        public MediaInfo $media,
        public ?array $issues = null,
    ) {}
}
