<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class TechSpec extends Dto
{
    /**
     * @param  TextComponent  $specKey  Rich text content.
     * @param  TextComponent  $specValue  Rich text content.
     */
    public function __construct(
        public TextComponent $specKey,
        public TextComponent $specValue,
    ) {}
}
