<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class TechSpecs extends Dto
{
    /**
     * @param  TechSpec  $techSpec  A single technical specification with a key-value pair.
     */
    public function __construct(
        public TechSpec $techSpec,
    ) {}
}
