<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ThreeColumnComparisonRow extends Dto
{
    protected static array $complexArrayTypes = ['metricValues' => MetricValueItem::class];

    /**
     * @param  ?int  $position  Location of the row within the comparison table. Must be a value between 1 and 5.
     * @param  MetricValueItem[]|null  $metricValues  The metric values for each of the three products in this row. Exactly three items are required.
     */
    public function __construct(
        public ?int $position = null,
        public ?array $metricValues = null,
    ) {}
}
