<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class ThreeColumnComparisonProduct extends Dto
{
    /**
     * @param  ?int  $position  Location of the product within the comparison table. Must be a value between 1 and 3.
     * @param  ?TextComponent  $productTitle  Rich text content.
     * @param  ?TextComponent  $productAsin  Rich text content.
     * @param  ?ImageComponent  $image  A reference to an image, hosted in the A+ Content media library.
     */
    public function __construct(
        public ?int $position = null,
        public ?TextComponent $productTitle = null,
        public ?TextComponent $productAsin = null,
        public ?ImageComponent $image = null,
    ) {}
}
