<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class UpdateMediaRequest extends Dto
{
    protected static array $complexArrayTypes = ['descriptions' => Description::class];

    /**
     * @param  ?string  $title  The updated title. When `associatedMediaId` query parameter is provided, updates the pairing title (minimum 3 words). When absent and `mediaId` is an image, updates the image title.
     * @param  Description[]|null  $descriptions  A list of locale-keyed accessibility descriptions. At least one entry is required for video assets.
     */
    public function __construct(
        public ?string $title = null,
        public ?array $descriptions = null,
    ) {}
}
