<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class VideoImageCarouselPanels extends Dto
{
    /**
     * @param  VideoImageCarouselPanel  $videoCarouselPanel  A single panel within the video/image carousel containing a video or image with optional text.
     */
    public function __construct(
        public VideoImageCarouselPanel $videoCarouselPanel,
    ) {}
}
