<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class VideoComponent extends Dto
{
    /**
     * @param  string  $videoMediaId  This identifier is provided by the create media response, used to locate an uploaded video file.
     * @param  string  $imageMediaId  This identifier is provided by the create media response, used to locate an uploaded image file.
     * @param  ImageCropSpecification  $imageCropSpecification  The instructions for optionally cropping an image. If no cropping is desired, set the dimensions to the original image size. If the image is cropped and no offset values are provided, then the coordinates of the top left corner of the cropped image, relative to the original image, are defaulted to (0,0).
     */
    public function __construct(
        public string $videoMediaId,
        public string $imageMediaId,
        public ImageCropSpecification $imageCropSpecification,
    ) {}
}
