<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class VideoImageCarouselPanel extends Dto
{
    /**
     * @param  int  $position  The position of the panel within the carousel. Must be a value between 1 and 6.
     * @param  ?TextComponent  $title  Rich text content.
     * @param  ?string  $positionType  The relative positioning of content.
     * @param  ?TextComponent  $subheadline  Rich text content.
     * @param  ?ParagraphComponent  $description  A list of rich text content, usually presented in a text box.
     * @param  ?ImageComponent  $desktopImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ?ImageComponent  $mobileImage  A reference to an image, hosted in the A+ Content media library.
     * @param  ?VideoComponent  $video  A reference to a video asset hosted within A+, including metadata and a preview thumbnail image.
     */
    public function __construct(
        public int $position,
        public ?TextComponent $title = null,
        public ?string $positionType = null,
        public ?TextComponent $subheadline = null,
        public ?ParagraphComponent $description = null,
        public ?ImageComponent $desktopImage = null,
        public ?ImageComponent $mobileImage = null,
        public ?VideoComponent $video = null,
    ) {}
}
