<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: SellingPartnerApi\Generator\Generators\ResponseGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Responses;

use SellingPartnerApi\Response;
use SellingPartnerApi\Seller\APlusContentV20201101\Dto\Description;
use SellingPartnerApi\Seller\APlusContentV20201101\Dto\Error;
use SellingPartnerApi\Seller\APlusContentV20201101\Dto\Issue;
use SellingPartnerApi\Seller\APlusContentV20201101\Dto\RelatedMedia;

final class GetMediaResponse extends Response
{
    protected static array $complexArrayTypes = [
        'warnings' => Error::class,
        'descriptions' => Description::class,
        'issues' => Issue::class,
        'relatedMedia' => RelatedMedia::class,
    ];

    /**
     * @param  string  $mediaId  The unique identifier for the media asset.
     * @param  string  $mediaType  The type of media asset.
     * @param  string  $title  The title for the media asset. For videos, this is the original filename. For images, this is the user-provided title or filename.
     * @param  string[]  $status  The composite status of the media asset. Multiple statuses can apply simultaneously to represent both the workflow stage and the responsible actor.
     * @param  Error[]|null  $warnings  A set of messages to the user, such as warnings or comments.
     * @param  Description[]|null  $descriptions  A list of locale-keyed accessibility descriptions. At least one entry is required for video assets.
     * @param  ?string  $mediaUrl  The CDN URL for downloading or viewing the media asset. The URL is provisioned at upload time and available in all statuses. The media is non-permanent; you should re-retrieve using `getMedia` rather than caching indefinitely.
     * @param  Issue[]|null  $issues  A list of issues associated with a media asset or pairing.
     * @param  RelatedMedia[]|null  $relatedMedia  A list of related media associations.
     */
    public function __construct(
        public readonly string $mediaId,
        public readonly string $mediaType,
        public readonly string $title,
        public readonly array $status,
        public readonly ?array $warnings = null,
        public readonly ?array $descriptions = null,
        public readonly ?string $mediaUrl = null,
        public readonly ?array $issues = null,
        public readonly ?array $relatedMedia = null,
    ) {}
}
