<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: SellingPartnerApi\Generator\Generators\RequestGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Requests;

use Exception;
use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Response;
use Saloon\Traits\Body\HasJsonBody;
use SellingPartnerApi\Request;
use SellingPartnerApi\Seller\APlusContentV20201101\Dto\CreateMediaRequest;
use SellingPartnerApi\Seller\APlusContentV20201101\Responses\CreateMediaResponse;
use SellingPartnerApi\Seller\APlusContentV20201101\Responses\ErrorList;

/**
 * createMedia
 */
class CreateMedia extends Request implements HasBody
{
    use HasJsonBody;

    protected Method $method = Method::POST;

    /**
     * @param  CreateMediaRequest  $createMediaRequest  The request body for creating a media asset. Uses the unified media shape as a subset, omitting system-derived fields.
     */
    public function __construct(
        public CreateMediaRequest $createMediaRequest,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/aplus/2020-11-01/media';
    }

    public function createDtoFromResponse(Response $response): CreateMediaResponse|ErrorList
    {
        $status = $response->status();
        $responseCls = match ($status) {
            200, 201 => CreateMediaResponse::class,
            400, 403, 404, 409, 410, 429, 500, 503 => ErrorList::class,
            default => throw new Exception("Unhandled response status: {$status}")
        };

        return $responseCls::deserialize($response->json());
    }

    public function defaultBody(): array
    {
        return $this->createMediaRequest->toArray();
    }
}
