<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: SellingPartnerApi\Generator\Generators\RequestGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Requests;

use Exception;
use Saloon\Enums\Method;
use Saloon\Http\Response;
use SellingPartnerApi\Request;
use SellingPartnerApi\Seller\APlusContentV20201101\Responses\ErrorList;
use SellingPartnerApi\Seller\APlusContentV20201101\Responses\GetMediaResponse;

/**
 * getMedia
 */
class GetMedia extends Request
{
    protected Method $method = Method::GET;

    /**
     * @param  string  $mediaId  The unique identifier for the media asset.
     * @param  ?string  $associatedMediaId  When provided, returns only the specific association. When omitted, returns all associated media.
     */
    public function __construct(
        protected string $mediaId,
        protected ?string $associatedMediaId = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return "/aplus/2020-11-01/media/{$this->mediaId}";
    }

    public function createDtoFromResponse(Response $response): GetMediaResponse|ErrorList
    {
        $status = $response->status();
        $responseCls = match ($status) {
            200 => GetMediaResponse::class,
            400, 403, 404, 410, 429, 500, 503 => ErrorList::class,
            default => throw new Exception("Unhandled response status: {$status}")
        };

        return $responseCls::deserialize($response->json());
    }

    public function defaultQuery(): array
    {
        return array_filter(['associatedMediaId' => $this->associatedMediaId]);
    }
}
