<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: SellingPartnerApi\Generator\Generators\RequestGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Requests;

use Exception;
use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Response;
use Saloon\Traits\Body\HasJsonBody;
use SellingPartnerApi\Request;
use SellingPartnerApi\Seller\APlusContentV20201101\Dto\UpdateMediaRequest;
use SellingPartnerApi\Seller\APlusContentV20201101\Responses\ErrorList;
use SellingPartnerApi\Seller\APlusContentV20201101\Responses\UpdateMediaResponse;

/**
 * updateMedia
 */
class UpdateMedia extends Request implements HasBody
{
    use HasJsonBody;

    protected Method $method = Method::PATCH;

    /**
     * @param  string  $mediaId  The unique identifier for the media asset to update.
     * @param  UpdateMediaRequest  $updateMediaRequest  The request body for updating media metadata. Exactly one of title or descriptions must be provided.
     * @param  ?string  $associatedMediaId  When provided, identifies the specific video-image pairing for title updates. Required when updating a pairing title.
     */
    public function __construct(
        protected string $mediaId,
        public UpdateMediaRequest $updateMediaRequest,
        protected ?string $associatedMediaId = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return "/aplus/2020-11-01/media/{$this->mediaId}";
    }

    public function createDtoFromResponse(Response $response): UpdateMediaResponse|ErrorList
    {
        $status = $response->status();
        $responseCls = match ($status) {
            200 => UpdateMediaResponse::class,
            400, 403, 404, 410, 429, 500, 503 => ErrorList::class,
            default => throw new Exception("Unhandled response status: {$status}")
        };

        return $responseCls::deserialize($response->json());
    }

    public function defaultBody(): array
    {
        return $this->updateMediaRequest->toArray();
    }

    public function defaultQuery(): array
    {
        return array_filter(['associatedMediaId' => $this->associatedMediaId]);
    }
}
